"""empty message

Revision ID: de08f7fe66f5
Revises: aa906b99e445
Create Date: 2026-02-01 18:08:08.571621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de08f7fe66f5'
down_revision = 'aa906b99e445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes_recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingredientes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredientes_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredientes_recetas')
    # ### end Alembic commands ###
